### ISSUE TITLE
C源码问题咨询

### ISSUE THREAD

**Issue by runaway** [tpoisonooo/chgemm#2]
请问MMult_4x8_19.c~MMult_4x8_21.c里面用到的reorder，int8kernel的C源码在哪里呀？我只看见有汇编的实现

**Comment by tpoisonooo** [comment]
1. MMult_4x8_19.c~MMult_4x8_20.c 主要是为了测试用，所以当时开发写了 C；

2. MMult_4x8_21.c 开始补全了所有尺寸，打算作为一个正式可实用到产品里的 int8 gemm 开发，是用汇编直接开发完成的，没有 c 过渡；

3. 考虑到兼容问题，c 版本需要补上。欢迎 PR。
