### ISSUE TITLE
int8kernel_m1.S ，int8kernel_m2.S ，int8kernel_m4.S 的区别是什么？

### ISSUE THREAD

**Issue by AnonymousYWL** [tpoisonooo/chgemm#5]

**Comment by tpoisonooo** [comment]
假如 GEMM 里 A 的尺寸是 MxN，M=7，N=4， 实际做是把 7 分解成 4 + 2 + 1。
先做 4x4 的 GEMM，再做 2x4，最后 1x4。

所有的 M 都可以分解成 4x + 2y + 1z。
